# Generated by Django 3.1.1 on 2020-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_office_office_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='new_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
