# Generated by Django 3.1.1 on 2020-09-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0016_auto_20200927_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='employee',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
