# Generated by Django 3.1.1 on 2020-09-24 10:49

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_auto_20200924_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='peopleWorking',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=[], size=None),
        ),
    ]
