# Generated by Django 3.1.1 on 2020-09-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_auto_20200924_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_id',
        ),
    ]
