# Generated by Django 3.1.1 on 2020-09-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_auto_20200925_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='office_owner',
        ),
    ]
