# Generated by Django 3.1.1 on 2020-09-24 18:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_auto_20200924_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='office',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='office.office'),
        ),
    ]
