# Generated by Django 3.1.1 on 2020-09-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_auto_20200924_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='office',
        ),
    ]
