# Generated by Django 3.1.1 on 2020-09-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_remove_person_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
