# Generated by Django 3.1.1 on 2020-09-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_auto_20200925_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
    ]
