# Generated by Django 3.1.1 on 2020-09-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_person_new_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='new_name',
        ),
    ]
