# Generated by Django 3.1.1 on 2020-09-25 05:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_office_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='employee',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='office.person', unique=True),
        ),
    ]
