# Generated by Django 3.1.1 on 2020-09-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_auto_20200925_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='employee',
        ),
    ]
