# Generated by Django 3.1.1 on 2020-09-25 06:57

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    Person = apps.get_model("office", "Person")
    for item in Person.objects.all():
        item.uuid = uuid.uuid4()
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0016_remove_office_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(create_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="person",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
