# Generated by Django 3.1.1 on 2020-09-25 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0018_auto_20200925_0910"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="office",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="office.office",
            ),
        ),
    ]
