# Generated by Django 3.1.1 on 2020-09-25 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0019_person_office"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="person_old",
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
