# Generated by Django 3.1.1 on 2020-09-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0020_person_person_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='office',
        ),
    ]
