# Generated by Django 3.1.1 on 2020-09-25 07:23

from django.db import migrations, models
import django.db.models.deletion


def copy_category_uuid(apps, schema_editor):
    Person = apps.get_model("office", "Person")
    person_uuid = Person.objects.filter(id=models.OuterRef("person_old")).values_list(
        "uuid"
    )[:1]
    Person.objects.update(category=models.Subquery(person_uuid))


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0021_remove_person_office"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="office",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="office.office",
            ),
        ),
        migrations.RunPython(
            copy_category_uuid, reverse_code=migrations.RunPython.noop
        ),
    ]
