# Generated by Django 3.1.1 on 2020-09-25 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0022_person_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_old',
        ),
        migrations.AlterField(
            model_name='person',
            name='office',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='office.office'),
            preserve_default=False,
        ),
    ]
