# Generated by Django 3.1.1 on 2020-09-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0023_auto_20200925_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='office',
        ),
    ]
