# Generated by Django 3.1.1 on 2020-09-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0024_remove_person_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='uuid',
            new_name='id',
        ),
    ]
